=== ph-developer/audesp-api/docs/edital-v4-20260203/edital_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "title": "Edital",
    "description": "JSON schema para o envio de editais de licitação/compra. Ano exercício: 2023/2024.",
    "type": "object",
    "properties": {

    "descritor": {
      "type": "object",
      "properties": {
			"municipio": {
			  "$id": "#root/descritor/municipio",
			  "title": "Municipio",
			  "type": "integer",
			  "minimum": 1,
			  "maximum": 9999
			},
			"entidade": {
			  "$id": "#root/descritor/entidade",
			  "title": "Entidade",
			  "type": "integer",
			  "minimum": 1,
			  "maximum": 99999
			},
			"codigoEdital": {
			  "$id": "#root/descritor/codigoEdital",
			  "title": "Código único que identifica o Edital original",
              "type": "string",
   			  "maxLength": 25
			},
			"dataDocumento": {
			  "$id": "#root/descritor/dataPublicacao",
			  "title": "Data do Edital ou data da retificação do Edital",
              "type": "string",
			  "format": "date"
			},
            "retificacao": {
			  "title": "Identifica se o documento é uma retificação; true - Retificação; false - Não é retificação",
			  "type": "boolean"
			}  
	  },
	  "required": [
		"municipio",
		"entidade",
        "codigoEdital",
        "dataDocumento",
        "retificacao"
	  ],
	  "additionalProperties": false
	},
		
    "publicidade": {
      "type": "object",
      "properties": {
			"houvePublicacao": {
			  "title": "Indica se o documento foi publicado",
			  "type": "boolean"
			},
		    "publicacoes": {
                "title": "Lista de publicações deste documento",
                "type": "array",
				"items": {
				  "description": "Publicação deste documento",
				  "type": "object",
				  "required": [
					 "dataPublicacao",
					 "veiculoPublicacao"
				  ],
				  "additionalProperties": false,
				  "properties": {
						  "dataPublicacao": {
						    "type": "string",
						    "format": "date"
						  },
						  "veiculoPublicacao": {
							"title": "Veículo usado para esta publicação.",
							"type": "integer",
							"enum": [1,2,3,4,5,6,7,8,9,10]
						  },
						  "idContratacaoPNCP": {
							"title": "No caso de publicação no PNCP (ou seja, veiculoPublicacao igual 5), informar o número de controle da contratação fornecido pelo PNCP (apenas caracteres numéricos).",
							"type": "string",
							"pattern": "^[0-9]{25}$",
							"maxLength": 25
                          },
						  "veiculoPublicacaoNome": {
							"title": "Informar o nome do veículo do veículo de publicação, caso o veículo de publicação indicado tenha sido Outros (veiculoPublicacao igual 10)",
							"type": "string",
							"maxLength": 100
						  }
	              }                      
                }
			}			
		  },
		  "required": [
			"houvePublicacao"
		  ],
		  "additionalProperties": false
	},



		"codigoUnidadeCompradora": {
			"description": "Código da unidade; A unidade deverá estar cadastrada para o órgão originário da contratação (proprietário da contratação ou alienação de bens)",
			"type": "string",
			"maxLength": 20
		},
		"tipoInstrumentoConvocatorioId": {
			"description": "Tipo de instrumento Convocatório",
			"type": "integer",
			 "enum": [1, 2, 3, 4]
		},
		"modalidadeId": {
			"description": "Modalidade de Compra/Contratação",
			"type": "integer",
			"enum": [1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 14, 997, 998, 999]
		},
		"modoDisputaId": {
			"description": "Modo de disputa",
			"type": "integer",
			"enum": [1, 2, 3, 4, 5, 6]
		},
		"numeroCompra": {
			"description": "Número da contratação no sistema de origem sem o ano. Esse número é gerado pelo usuário no seu sistema de origem (ex. Pregão 14)",
			"type": "string",
			"maxLength": 50
		},
		"anoCompra": {
			"description": "Ano da contratação. Esse é o ano relacionado ao número da contratação. (Ex: 2021)",
			"type": "integer",
			"inclusiveMinimum": 1970,
			"inclusiveMaximum": 2099
		},
		"numeroProcesso": {
			"description": "Número do processo de contratação no sistema de origem",
			"type": "string",
			"maxLength": 50
		},
		"objetoCompra": {
			"description": "Objeto da contratação",
			"type": "string",
			"maxLength": 5120
		},
		"informacaoComplementar": {
			"description": "Informações complementares; Se houver;",
			"type": "string",
			"maxLength": 5120
		},
		"srp": {
			"description": "Identifica se a compra trata-se de um SRP (Sistema de registro de preços).",
			"type": "boolean"
		},
		"dataAberturaProposta": {
			"description": "data e hora de início do recebimento das propostas (pelo horário de Brasília)",
			"type": "string",
			"maxLength": 19,			
			"pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}$"
		},
		"dataEncerramentoProposta": {
			"description": "data e hora de encerramento do recebimento das propostas (pelo horário de Brasília)",
			"type": "string",
			"maxLength": 19,			
			"pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}$"
		},
		"amparoLegalId": {
			"description": "Amparo legal para dispensa ou inexigibilidade",
			"type": "integer",
			"enum": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,
                     17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,
                     33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,50,
                     60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,
                     76,77,78,81,82,83,84,85,86,87,88,89,90,91,92,93,
                     94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,
                     110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,
                     126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,
                     142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,
					 158,159,160,162,163,164,165,
                     964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,
                     980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,
                     996,997,998,999,1019,1020
            ]
		},
		"linkSistemaOrigem": {
			"description": "url do sistema de origem para envio de proposta/lance",
			"type": "string",
			"minimum": 1,
			"maxLength": 500
		},
		"justificativaPresencial": {
			"description": "justificativa pela escolha da modalidade presencial",
			"type": "string",
			"minimum": 1,
			"maxLength": 500
		},
		"itensCompra": {
                "title": "Lista de itens da contratação",
                "type": "array",
                "minItems": 1,
				"items": {
				  "description": "Item da contratação",
				  "type": "object",
				  "required": [
					  "numeroItem",
					  "materialOuServico",
					  "tipoBeneficioId",
					  "incentivoProdutivoBasico",
					  "descricao",
					  "quantidade",
					  "unidadeMedida",
					  "orcamentoSigiloso",
					  "valorUnitarioEstimado",
					  "valorTotal",
					  "criterioJulgamentoId",
					  "itemCategoriaId"
				  ],
				  "additionalProperties": false,
				  "properties": {
						  "numeroItem": {
							"title": "Número do item na contratação (único e sequencial crescente)",
							"type": "integer"
						  },
						  "materialOuServico": {
							"title": "M - Material; S - Serviço",
							"type": "string",
							"minLength": 1,
							"maxLength": 1
						  },
						  "tipoBeneficioId": {
							"title": "Tipo de benefício",
							"type": "integer",
							"enum": [1,2,3,4,5]
                          },
						  "incentivoProdutivoBasico": {
							"title": "Incentivo fiscal PPB (Processo Produtivo Básico); true - Possui o incentivo; false - Não possui o incentivo;",
							"type": "boolean"
						  },
						  "descricao": {
							"title": "Descrição para o produto ou serviço",
							"type": "string",
							"minLength": 1,
							"maxLength": 2048
						  },
						  "quantidade": {
							"title": "Quantidade do item da contratação. Precisão de 4 dígitos decimais; Ex: 100.0000",
							"type": "number"						  
						  },
						  "unidadeMedida": {
							"title": "Unidade de medida do item da contratação",
							"type": "string",
							"minLength": 1,
							"maxLength": 30
						  },
						  "orcamentoSigiloso": {
							"title": "Identifica se o orçamento do item é sigiloso; true - Sigiloso; false - Não sigiloso",
							"type": "boolean"
						  },
						  "valorUnitarioEstimado" : {
							"title": "Valor unitário estimado para o item da contratação. Precisão de 4 dígitos decimais; Ex: 100.0000",
							"type": "number"						  
						  },
						  "valorTotal" : {
							"title": "Valor total para contratação tradicional. Precisão de 4 dígitos decimais; Ex: 100.0000",
							"type": "number"						  
						  },
						  "criterioJulgamentoId": {
							"title": "Critério de julgamento",
							"type": "integer",
							"enum": [1,2,4,5,6,7,8,9,1000,1001]
                          },
						  "itemCategoriaId": {
							"title": "Categoria do item. Domínios 1 ou 2 aplicados à modalidade leilão. Outras modalidades de contratação utilizar o domínio 3. Domínio: 1 – Bens Imóveis; 2 – Bens Móveis; 3 - Não se aplica",
							"type": "integer",
							"enum": [1,2,3]
                          },
						  "patrimonio": {
							"title": "Código de Patrimonio do Item de bens móveis quando existir.",
							"type": "string",
							"minLength": 1,
							"maxLength": 255
						  },
						  "codigoRegistroImobiliario": {
							"title": "Código de Registro Imobiliário",
							"type": "string",
							"minLength": 1,
							"maxLength": 255
						  }
	              }                      
                }
			  }
    },
    "required": [
        "descritor",
		"publicidade",
		"tipoInstrumentoConvocatorioId",
		"modalidadeId",
		"modoDisputaId",
		"numeroCompra",
		"anoCompra",
		"numeroProcesso",
		"objetoCompra",
		"srp",
		"amparoLegalId",
		"itensCompra"
    ]
}

=== ph-developer/audesp-api/docs/edital-v4-20260203/edital_exemplo.json
{
    "descritor": {
      "municipio": 7107,
      "entidade": 10048,
      "codigoEdital": "202410227000",
      "dataDocumento": "2024-10-10",
      "retificacao": false
    },
    "publicidade": {
      "houvePublicacao": true,
      "publicacoes": [
        {
          "dataPublicacao": "2023-12-05",
          "veiculoPublicacao": 2
        },
        {
          "dataPublicacao": "2024-01-01",
          "veiculoPublicacao": 5,
          "idContratacaoPNCP": "5029093100014010000022024"
        }
      ]
    },
    "tipoInstrumentoConvocatorioId": 1,
    "modalidadeId": 6,
    "modoDisputaId": 1,
    "numeroCompra": "0001",
    "anoCompra": 2023,
    "numeroProcesso": "1/2023",
    "objetoCompra": "Descricao do objeto da contratacao",
    "informacaoComplementar": "",
    "srp": false,
    "dataAberturaProposta": "2023-07-21T08:00:00",
    "dataEncerramentoProposta": "2023-07-21T17:00:00",
    "amparoLegalId": 1,
    "linkSistemaOrigem": "url do sistema de origem para envio de proposta/lance",
    "itensCompra": [
      {
        "numeroItem": 1,
        "materialOuServico": "S",
        "tipoBeneficioId": 4,
        "incentivoProdutivoBasico": false,
        "descricao": "Item do tipo servico",
        "quantidade": 1000,
        "unidadeMedida": "Unidade",
        "orcamentoSigiloso": false,
        "valorUnitarioEstimado": 1.5001,
        "valorTotal": 1500,
        "criterioJulgamentoId": 1,
        "itemCategoriaId": 3,
        "patrimonio": "string",
        "codigoRegistroImobiliario": "string"
      },
      {
        "numeroItem": 2,
        "materialOuServico": "M",
        "tipoBeneficioId": 4,
        "incentivoProdutivoBasico": false,
        "descricao": "Item do tipo material",
        "quantidade": 10,
        "unidadeMedida": "Kilograma",
        "orcamentoSigiloso": false,
        "valorUnitarioEstimado": 100,
        "valorTotal": 1000,
        "criterioJulgamentoId": 1,
        "itemCategoriaId": 3,
        "patrimonio": "string",
        "codigoRegistroImobiliario": "string"
      }
    ] 
}
